"""Bulk CSV publisher for Pinterest -> Amazon affiliate pins.

KEY: does NOT need the (pending) developer-app approval. Uses Pinterest's
native BULK UPLOAD (Business account: Settings > Import content > Upload .csv).
The CSV carries FULL content: Title, Media URL, Board, Description, Link,
Publish date (UTC future = scheduled), Keywords.

Flow:
  1. hero images live in D:/repos/pinterest-affiliate/assets/<slug>.png
     (generated by Hermes image_generate = the Designer step)
  2. push_images() copies them to D:/repos/pinterest-pins/images/ and git-pushes
     (GitHub Pages serves them publicly)
  3. build_csv() writes bulk_upload.csv with the public media URLs

USAGE (in this repo):  python bulk_publisher.py
"""
import csv
import json
import os
import shutil
import subprocess

THIS_REPO = os.path.dirname(os.path.abspath(__file__))
AFFILIATE_REPO = "D:/repos/pinterest-pins"
AFFILIATE_IMG_DIR = os.path.join(AFFILIATE_REPO, "images")
ASSETS_DIR = os.path.join(THIS_REPO, "assets")
PAGES_BASE = "https://lexxautomates.github.io/pinterest-pins/images"


def push_images():
    os.makedirs(AFFILIATE_IMG_DIR, exist_ok=True)
    copied = []
    for f in os.listdir(ASSETS_DIR):
        if f.lower().endswith((".png", ".jpg", ".jpeg")) and f not in ("test_pin.png",):
            shutil.copy(os.path.join(ASSETS_DIR, f), os.path.join(AFFILIATE_IMG_DIR, f))
            copied.append(f)
    if not copied:
        return copied
    subprocess.run(["git", "-C", AFFILIATE_REPO, "add", "-A"], check=False)
    subprocess.run(["git", "-C", AFFILIATE_REPO, "-c", "user.email=lexxautomates@gmail.com",
                    "-c", "user.name=lexxautomates", "commit", "-q",
                    "-m", "add pin images"], check=False)
    subprocess.run(["git", "-C", AFFILIATE_REPO, "push"], check=False)
    return copied


def build_csv(pins, out="bulk_upload.csv"):
    """pins: list of dicts {slug,title,description,link,board,keywords,publish_date}"""
    rows = []
    for p in pins:
        rows.append({
            "Title": p["title"][:100],
            "Media URL": f"{PAGES_BASE}/{p['slug']}.png",
            "Pinterest board": p["board"],
            "Description": p["description"][:500],
            "Link": p["link"],
            "Publish date": p.get("publish_date", ""),
            "Keywords": p["keywords"],
        })
    path = os.path.join(THIS_REPO, out)
    with open(path, "w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=["Title", "Media URL", "Pinterest board",
                                           "Description", "Link", "Publish date", "Keywords"])
        w.writeheader()
        w.writerows(rows)
    return path, rows


if __name__ == "__main__":
    staged = os.path.join(THIS_REPO, "queue", "staged_pins.json")
    if not os.path.exists(staged):
        print("no staged pins; run agent_orchestrator.py first")
    else:
        data = json.load(open(staged))
        copied = push_images()
        pins = []
        for i, t in enumerate(data):
            slug = f"pin_{i+1}_{t.get('niche','x')}"
            pins.append({
                "slug": slug,
                "title": t["title"],
                "description": t["description"],
                "link": t["link"],
                "board": t.get("niche", "amazon-finds").replace("_", " ").title(),
                "keywords": f"{t.get('niche','amazon')},amazonfinds,musthaves,shopping",
                "publish_date": "",
            })
        path, rows = build_csv(pins)
        print(f"Pushed {len(copied)} images; wrote {path} with {len(rows)} rows")
